name: Bug Report
description: Report a bug to help us improve
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! 🐛
        
        **Before submitting**: Please check if there's already an issue for this bug.
        
        **Consider contributing**: If you've found a solution, we'd love a pull request!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g. Windows 11, macOS 12, Ubuntu 20.04]
        - Python Version: [e.g. 3.9.7]
        - Browser: [e.g. Chrome 96, Firefox 95]
        - Database: [e.g. PostgreSQL 13.4]
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including logs or screenshots.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute a fix?
      options:
        - label: I'm interested in contributing a fix for this issue
          required: false
        - label: I need guidance on how to fix this
          required: false
