name: 🤖 Automated Data Ingestion

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📋 Install dependencies
        run: |
          pip install -r requirements.txt

      - name: 🔍 Run ingestion scripts
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          echo "🚀 Starting automated ingestion..."
          python -m ingest.github_ingest
          python -m ingest.arxiv_ingest
          python -m ingest.hf_ingest
          python -m ingest.pwc_ingest
          python -m dedup.dedup
          echo "✅ Ingestion complete!"

      - name: 📊 Report status
        run: |
          echo "🎉 Successfully updated AI agent database!"
          echo "📈 Check the API at your deployed URL for latest data"
